### ISSUE TITLE
bug: autocomplete not working "Expected to receive exactly one message with the prompt" 

### ISSUE THREAD

**Issue by quentin-lior** [sourcegraph/cody#4639] opened 2024-06-21 07:07 UTC
### Version

1.22.4

### Describe the bug

My Cody autocomplete is not working (the setting "Enables code autocompletions" is checked), but the chat feature is working fine. In the ouptut console, I noticed the following errors

 getInlineCompletions:error: error parsing CodeCompletionResponse: Error: {"error":"Expected to receive exactly one message with the prompt"} Error: error parsing CodeCompletionResponse: Error: {"error":"Expected to receive exactly one message with the prompt"}
    at /Users/quentin/.vscode/extensions/sourcegraph.cody-ai-1.22.4/src/completions/client.ts:224:27
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at generatorWithTimeout (/Users/quentin/.vscode/extensions/sourcegraph.cody-ai-1.22.4/src/completions/utils.ts:84:37)
    at generatorWithErrorObserver (/Users/quentin/.vscode/extensions/sourcegraph.cody-ai-1.22.4/src/completions/utils.ts:51:29)
    at fetchAndProcessDynamicMultilineCompletions (/Users/quentin/.vscode/extensions/sourcegraph.cody-ai-1.22.4/src/completions/providers/fetch-and-process-completions.ts:92:62)
    at async Promise.all (index 0)
    at zipGenerators (/Users/quentin/.vscode/extensions/sourcegraph.cody-ai-1.22.4/src/completions/utils.ts:34:21)
    at generateCompletions (/Users/quentin/.vscode/extensions/sourcegraph.cody-ai-1.22.4/src/completions/request-manager.ts:118:34)

### Expected behavior

Cody should propose autocomplete functionality when starting to write code in editor

### Additional context

I am working on python files right now.
MacOS : Sonoma 14.5
VS Code : 1.90.2

**Comment by pedanticgeek** [comment] 2024-06-29 02:02
Same here.
VSCode: 1.90.2
MacOS: 14.4.1
Cody: 1.24

Working with TypeScript

**Comment by quentin-lior** [comment] 2024-07-03 20:16
I somehow managed to get autocomplete to work. 
In Cody settings, I noticed that cody.autocomplete.advanced.provider was set to "Anthropic". However, it looks like the default value is "null", so when switching to "null", the autocomplete worked again as expected.

**Comment by justinmilner1** [comment] 2024-07-03 23:08
Hey guys @quentin-lior @pedanticgeek

- Which provider are you using for autocomplete?
- Does this happen for every completion? Or just occasionally?

I traced the error back to its source in the [external shared sourcegraph library](https://github.com/sourcegraph/sourcegraph/blob/main/internal/completions/client/azureopenai/openai.go) - but it looks like there could be a lot of reasons why the request isn't as expected. Hoping to get [this PR](https://github.com/sourcegraph/sourcegraph/pull/63628) with more descriptive logging into sourcegraph to narrow things down a bit.

**Comment by justinmilner1** [comment] 2024-07-03 23:47
Ah okay, I was able to replicate this - it's because Anthropic isn't implemented as a autocomplete provider yet - it shouldn't be in the list. 
Removed the anthropic option in [this PR](https://github.com/sourcegraph/cody/pull/4775)

**Comment by vadi2** [comment] 2024-07-06 15:38
I can confirm that switching it back to `null` does the trick.

**Comment by justinmilner1** [comment] 2024-07-07 14:56
Looks like there was a parameter that wasn't being assigned a default value when it was undefined. Fixed in [this PR](https://github.com/sourcegraph/cody/pull/4803/files)

**Comment by arunsathiya** [comment] 2024-08-27 22:37
I see the same behavior with [the latest release of 1.33.1724685353 as well](https://marketplace.visualstudio.com/items?itemName=sourcegraph.cody-ai&ssr=false#version-history). I am not saying it's happening only on the latest release, just that I am on the latest release at the moment.

**Comment by valerybugakov** [comment] 2024-08-28 05:27
@arunsathiya, could you share your Cody settings from the `settings.json` if you have any? Also, could you share the output of the debug logs (command: `Cody Debug: Open Output Channel,` reload VS Code, and paste the contents of the output here)?

**Comment by arunsathiya** [comment] 2024-08-28 05:49
@valerybugakov, I am not sure where I can find `settings.json` file—could you direct me to it?

Output of debug logs below:

```
█ telemetry-v2: recordEvent: cody.extension/savedLogin 
█ AuthProvider:init:lastEndpoint: Token recovered from secretStorage https://sourcegraph.com/
█ GraphQLTelemetryExporter: evaluated export mode: 5.2.5+
█ CodyLLMConfiguration: {"chatModel":"anthropic/claude-3-sonnet-20240229","chatModelMaxTokens":12000,"fastChatModel":"anthropic/claude-3-haiku-20240307","fastChatModelMaxTokens":12000,"completionModel":"fireworks/starcoder","completionModelMaxTokens":9000,"provider":"sourcegraph","smartContextWindow":true}
█ ClientConfigSingleton: refreshing configuration
█ ClientConfigSingleton: refreshed {"codyEnabled":true,"chatEnabled":true,"autoCompleteEnabled":true,"customCommandsEnabled":true,"attributionEnabled":false,"smartContextWindowEnabled":true,"modelsAPIEnabled":false}
█ ModelsService: Setting primary models: ["anthropic/claude-3-5-sonnet-20240620","anthropic/claude-3-opus-20240229","anthropic/claude-3-haiku-20240307","openai/gpt-4o","google/gemini-1.5-flash-latest","google/gemini-1.5-pro-latest","fireworks/accounts/fireworks/models/mixtral-8x7b-instruct","fireworks/accounts/fireworks/models/mixtral-8x22b-instruct"]
█ telemetry-v2: recordEvent: cody.auth/connected 
█ SymfRunner: unsafeEnsureIndex file:///Users/arun/portfolio
█ ChatsController:constructor: init
█ featureflag: refreshed
█ CodyCompletionProvider:initialized: anthropic/fireworks/starcoder
█ CodyCompletionProvider:initialized: anthropic/fireworks/starcoder
█ CodyCompletionProvider:initialized: anthropic/fireworks/starcoder
█ featureflag: refreshed
█ featureflag: refreshed
█ featureflag: refreshed
█ featureflag: refreshed
█ featureflag: refreshed
█ featureflag: refreshed
█ featureflag: refreshed
█ featureflag: refreshed
█ featureflag: refreshed
█ featureflag: refreshed
█ ContextFiltersProvider: setContextFilters 
█ ChatController: postContextStatus [{"displayName":"portfolio","providers":[{"kind":"search","type":"local","state":"ready"}]}]
█ featureflag: refreshed
█ UpstreamHealth: Ping took 135ms (Gateway: 113ms) 
█ ClientConfigSingleton: refreshing configuration
█ CompletionLogger:onError: {"type":"completion","endpoint":"https://sourcegraph.com/.api/completions/code?client-name=vscode&client-version=1.32.3","status":"error","duration":173,"err":"error parsing CodeCompletionResponse: Error: {\"error\":\"Expected to receive exactly one message with the prompt\"}"} 
█ getInlineCompletions:error: error parsing CodeCompletionResponse: Error: {"error":"Expected to receive exactly one message with the prompt"} Error: error parsing CodeCompletionResponse: Error: {"error":"Expected to receive exactly one message with the prompt"}
	at /Users/arun/.vscode/extensions/sourcegraph.cody-ai-1.32.3/dist/extension.node.js:194001:17
	at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
	at async generatorWithTimeout (/Users/arun/.vscode/extensions/sourcegraph.cody-ai-1.32.3/dist/extension.node.js:171241:31)
	at async generatorWithErrorObserver (/Users/arun/.vscode/extensions/sourcegraph.cody-ai-1.32.3/dist/extension.node.js:171218:21)
	at async fetchAndProcessDynamicMultilineCompletions (/Users/arun/.vscode/extensions/sourcegraph.cody-ai-1.32.3/dist/extension.node.js:191898:62)
	at async Promise.all (index 0)
	at async zipGenerators (/Users/arun/.vscode/extensions/sourcegraph.cody-ai-1.32.3/dist/extension.node.js:171207:17)
	at async generateCompletions (/Users/arun/.vscode/extensions/sourcegraph.cody-ai-1.32.3/dist/extension.node.js:192197:26)
█ telemetry-v2: recordEvent: cody.completion/error 
█ ClientConfigSingleton: refreshed {"codyEnabled":true,"chatEnabled":true,"autoCompleteEnabled":true,"customCommandsEnabled":true,"attributionEnabled":false,"smartContextWindowEnabled":true,"modelsAPIEnabled":false}
█ CompletionLogger:onError: {"type":"completion","endpoint":"https://sourcegraph.com/.api/completions/code?client-name=vscode&client-version=1.32.3","status":"error","duration":118,"err":"error parsing CodeCompletionResponse: Error: {\"error\":\"Expected to receive exactly one message with the prompt\"}"} 
█ getInlineCompletions:error: error parsing CodeCompletionResponse: Error: {"error":"Expected to receive exactly one message with the prompt"} Error: error parsing CodeCompletionResponse: Error: {"error":"Expected to receive exactly one message with the prompt"}
	at /Users/arun/.vscode/extensions/sourcegraph.cody-ai-1.32.3/dist/extension.node.js:194001:17
	at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
	at async generatorWithTimeout (/Users/arun/.vscode/extensions/sourcegraph.cody-ai-1.32.3/dist/extension.node.js:171241:31)
	at async generatorWithErrorObserver (/Users/arun/.vscode/extensions/sourcegraph.cody-ai-1.32.3/dist/extension.node.js:171218:21)
	at async fetchAndProcessDynamicMultilineCompletions (/Users/arun/.vscode/extensions/sourcegraph.cody-ai-1.32.3/dist/extension.node.js:191898:62)
	at async Promise.all (index 0)
	at async zipGenerators (/Users/arun/.vscode/extensions/sourcegraph.cody-ai-1.32.3/dist/extension.node.js:171207:17)
	at async generateCompletions (/Users/arun/.vscode/extensions/sourcegraph.cody-ai-1.32.3/dist/extension.node.js:192197:26)
█ CompletionLogger:onError: {"type":"completion","endpoint":"https://sourcegraph.com/.api/completions/code?client-name=vscode&client-version=1.32.3","status":"error","duration":168,"err":"error parsing CodeCompletionResponse: Error: {\"error\":\"Expected to receive exactly one message with the prompt\"}"} 
█ getInlineCompletions:error: error parsing CodeCompletionResponse: Error: {"error":"Expected to receive exactly one message with the prompt"} Error: error parsing CodeCompletionResponse: Error: {"error":"Expected to receive exactly one message with the prompt"}
	at /Users/arun/.vscode/extensions/sourcegraph.cody-ai-1.32.3/dist/extension.node.js:194001:17
	at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
	at async generatorWithTimeout (/Users/arun/.vscode/extensions/sourcegraph.cody-ai-1.32.3/dist/extension.node.js:171241:31)
	at async generatorWithErrorObserver (/Users/arun/.vscode/extensions/sourcegraph.cody-ai-1.32.3/dist/extension.node.js:171218:21)
	at async fetchAndProcessDynamicMultilineCompletions (/Users/arun/.vscode/extensions/sourcegraph.cody-ai-1.32.3/dist/extension.node.js:191898:62)
	at async Promise.all (index 0)
	at async zipGenerators (/Users/arun/.vscode/extensions/sourcegraph.cody-ai-1.32.3/dist/extension.node.js:171207:17)
	at async generateCompletions (/Users/arun/.vscode/extensions/sourcegraph.cody-ai-1.32.3/dist/extension.node.js:192197:26)
█ CompletionLogger:onError: {"type":"completion","endpoint":"https://sourcegraph.com/.api/completions/code?client-name=vscode&client-version=1.32.3","status":"error","duration":181,"err":"error parsing CodeCompletionResponse: Error: {\"error\":\"Expected to receive exactly one message with the prompt\"}"} 
█ getInlineCompletions:error: error parsing CodeCompletionResponse: Error: {"error":"Expected to receive exactly one message with the prompt"} Error: error parsing CodeCompletionResponse: Error: {"error":"Expected to receive exactly one message with the prompt"}
	at /Users/arun/.vscode/extensions/sourcegraph.cody-ai-1.32.3/dist/extension.node.js:194001:17
	at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
	at async generatorWithTimeout (/Users/arun/.vscode/extensions/sourcegraph.cody-ai-1.32.3/dist/extension.node.js:171241:31)
	at async generatorWithErrorObserver (/Users/arun/.vscode/extensions/sourcegraph.cody-ai-1.32.3/dist/extension.node.js:171218:21)
	at async fetchAndProcessDynamicMultilineCompletions (/Users/arun/.vscode/extensions/sourcegraph.cody-ai-1.32.3/dist/extension.node.js:191898:62)
	at async Promise.all (index 0)
	at async zipGenerators (/Users/arun/.vscode/extensions/sourcegraph.cody-ai-1.32.3/dist/extension.node.js:171207:17)
	at async generateCompletions (/Users/arun/.vscode/extensions/sourcegraph.cody-ai-1.32.3/dist/extension.node.js:192197:26)
█ CompletionLogger:onError: {"type":"completion","endpoint":"https://sourcegraph.com/.api/completions/code?client-name=vscode&client-version=1.32.3","status":"error","duration":128,"err":"error parsing CodeCompletionResponse: Error: {\"error\":\"Expected to receive exactly one message with the prompt\"}"} 
█ getInlineCompletions:error: error parsing CodeCompletionResponse: Error: {"error":"Expected to receive exactly one message with the prompt"} Error: error parsing CodeCompletionResponse: Error: {"error":"Expected to receive exactly one message with the prompt"}
	at /Users/arun/.vscode/extensions/sourcegraph.cody-ai-1.32.3/dist/extension.node.js:194001:17
	at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
	at async generatorWithTimeout (/Users/arun/.vscode/extensions/sourcegraph.cody-ai-1.32.3/dist/extension.node.js:171241:31)
	at async generatorWithErrorObserver (/Users/arun/.vscode/extensions/sourcegraph.cody-ai-1.32.3/dist/extension.node.js:171218:21)
	at async fetchAndProcessDynamicMultilineCompletions (/Users/arun/.vscode/extensions/sourcegraph.cody-ai-1.32.3/dist/extension.node.js:191898:62)
	at async Promise.all (index 0)
	at async zipGenerators (/Users/arun/.vscode/extensions/sourcegraph.cody-ai-1.32.3/dist/extension.node.js:171207:17)
	at async generateCompletions (/Users/arun/.vscode/extensions/sourcegraph.cody-ai-1.32.3/dist/extension.node.js:192197:26)
```

**Comment by arunsathiya** [comment] 2024-08-28 06:19
I found the `settings.json` file:

```json
{
  "[javascript]": {
    "editor.defaultFormatter": "esbenp.prettier-vscode"
  },
  "[python]": {
    "editor.defaultFormatter": "ms-python.python"
  },
  "[typescript]": {
    "editor.defaultFormatter": "vscode.typescript-language-features"
  },
  "editor.accessibilitySupport": "off",
  "editor.formatOnSave": true,
  "editor.minimap.enabled": false,
  "editor.wordWrap": "on",
  "explorer.confirmDelete": false,
  "github.copilot.enable": {
    "*": false,
    "plaintext": false,
    "markdown": false,
    "scminput": false,
    "go": false,
    "javascript": true,
    "typescript": false
  },
  "go.toolsManagement.autoUpdate": true,
  "jupyter.askForKernelRestart": false,
  "notebook.output.scrolling": true,
  "notebook.output.textLineLimit": 300,
  "python.analysis.autoImportCompletions": true,
  "terminal.integrated.env.osx": {
    "CW_NEW_SESSION": "1"
  },
  "editor.inlineSuggest.suppressSuggestions": true,
  "cody.autocomplete.enabled": true,
  "[typescriptreact]": {
    "editor.defaultFormatter": "esbenp.prettier-vscode"
  },
  "window.zoomLevel": 2,
  "github.copilot.editor.enableAutoCompletions": false,
  "cody.autocomplete.advanced.provider": "anthropic",
  "workbench.colorTheme": "Default Light Modern"
}
```

`github.copilot.editor.enableAutoCompletions` was enabled. I thought disabling it would help, but I don't see autocomplete from Cody and the same error, even after setting GitHub copilot autocompletions to false.

**Comment by valerybugakov** [comment] 2024-08-29 02:02
Thanks for sharing, @arunsathiya! Please remove `"cody.autocomplete.advanced.provider": "anthropic"` from your settings and try again. I'll dig into the issue with the `anthropic` provider today and come back to this thread.

**Closed** 2024-08-29 08:51 UTC
Labels: bug, clients/vscode

**Comment by arunsathiya** [comment] 2024-08-29 17:10
>UPD: going to fix this issue in today's patch release. We recommend using the default settings for autocomplete, which means removing all the cody.autocomplete.advanced.* settings from your local config. 

Thanks @valerybugakov! Just so I have a better understanding, does this mean that the model in use is not exactly Anthropic's Claude?

**Comment by miklereverie** [comment] 2024-08-29 20:09
> > UPD: going to fix this issue in today's patch release. We recommend using the default settings for autocomplete, which means removing all the cody.autocomplete.advanced.* settings from your local config.
> 
> Thanks @valerybugakov! Just so I have a better understanding, does this mean that the model in use is not exactly Anthropic's Claude?

I have the same question, just for clarity's sake, which model is the autocomplete using? 
Thanks for the amazing work, you do!

**Comment by valerybugakov** [comment] 2024-08-30 03:23
If you set the autocomplete provider to `anthropic`, Cody will use `claude-instant-1.2` for inference. It should be fixed in [the latest patch release](https://github.com/sourcegraph/cody/releases/tag/vscode-v1.32.5). 

The recommended setup (when you don't have any provider set in your settings) is different: `deepseek-v2-lite-base` hosted by Fireworks. We continuously iterate on it and switch models under the hood to get the best balance between latency and quality. 

If you're curious, you can learn more about our recent findings here: https://sourcegraph.com/blog/improving-cody-autocomplete-faster-smarter. Let me know if you have any other questions!

**Comment by AllyourBaseBelongToUs** [comment] 2024-09-04 12:20
> If you set the autocomplete provider to `anthropic`, Cody will use `claude-instant-1.2` for inference. The bug you experienced [here](https://github.com/sourcegraph/cody/issues/4639#issuecomment-2314371019) should be fixed in [the latest patch release](https://github.com/sourcegraph/cody/releases/tag/vscode-v1.32.5).
> 
> The recommended setup (when you don't have any provider set in your settings) is different: `deepseek-v2-lite-base` hosted by Fireworks. We continuously iterate on it and switch models under the hood to get the best balance between latency and quality.
> 
> If you're curious, you can learn more about our recent findings here: https://sourcegraph.com/blog/improving-cody-autocomplete-faster-smarter. Let me know if you have any other questions!

deepseek-v2 is decent but lacking in fixing issues after completion, even when obvious ones are present.

I love how fast it is, but must admit the Tab Tab Tab feature of Cursor AI is much better at that and quality is higher.

**Comment by anurag007m** [comment] 2025-02-05 16:54
<img width="507" alt="Image" src="https://github.com/user-attachments/assets/6b2ad9d8-a1ba-49f6-819b-65b317bd969e" /> 

Before it was  "cody.autocomplete.enabled": false and it was not working.
I made it to true   "cody.autocomplete.enabled": true, and now cody auto complete started working for me.Let me if it works for you all.
