### ISSUE TITLE
bug: `Error: Failed to get git output.` when using commit generation

### ISSUE THREAD

**Issue by A2va** [sourcegraph/cody#4863] opened 2024-07-14 19:27 UTC
### Version

v1.26.2

### Describe the bug

After clicking on the commit generation button, the text entry for the commit message is filled with `Error: Failed to get git output.`
This happens regardless of whether some files are staged or not.
![image](https://github.com/user-attachments/assets/7b67ec75-8ac7-46c3-b003-3dcb74a25c30)

### Expected behavior

The commit message should be generated.

### Additional context

Git output from the vscode session:

```
2024-07-14 21:24:48.285 [info] > git config --local commit.template [85ms]
2024-07-14 21:24:48.285 [warning] git config failed: Failed to execute git
2024-07-14 21:24:48.297 [info] > git config --global commit.template [90ms]
2024-07-14 21:24:48.297 [warning] git config failed: Failed to execute git
2024-07-14 21:24:48.412 [info] > git diff --name-status -z --diff-filter=ADMR --cached [107ms]
2024-07-14 21:24:48.420 [info] > git diff --name-status -z --diff-filter=ADMR [108ms]
2024-07-14 21:24:48.432 [info] > git log --format=%H%n%aN%n%aE%n%at%n%ct%n%P%n%D%n%B -z -n5 [113ms]
2024-07-14 21:24:48.509 [info] > git diff --cached [82ms]
```
OS: Windows 11

**Comment by ichim-david** [comment] 2024-08-02 07:36
Same issue on Mac Sonoma

**Comment by ichim-david** [comment] 2024-08-08 17:25
I think it has todo with more than one source of git repos.
In my case I have a react project which has a github repository and inside a src/addons I have several add-ons that have their own repo.
I am trying to create the commit message usually on these add-ons but even on the root it fails.
In order for VS Code to see those git remotes I had to make a workspace for the repo project and then add to the worspace the add-ons folder.

For another project where it's just the main repo I was able to finally get the commit message functionality to create a message.

Do be determined if this feedback is as any use :)

**Comment by ichim-david** [comment] 2024-08-30 07:31
@jdorfman @sqs can this issue get some love? It seems that Cody tries todo the git commit from the workspace path.
have a  look at this screenshot
![cody-git](https://github.com/user-attachments/assets/0d35c538-6c4e-4457-a6b5-a502860087d4)

from my project https://github.com/eea/eea-website-frontend
It's a react project with some packages inside src/addons folder.
Each folder is another git clone, for example https://github.com/eea/volto-eea-website-policy/

I have 2 workspaces set (one within eea-website-frontend and another inside src/addons). Regardless of the opened workspace I cannot trigger the commit message because it doesn't take into account the repo where the button was clicked.
In my screenshot I triggered from src/addons/volto-eea-website-policy and it was complaining about /src/addons not being a git repo.

Until Cody correctly processes these repos with multiple git clones and takes into account where it was triggered this feature won't work.
I am surprised that there aren't more complaints about this issue, I would of expected for this type of project to be very common where you have more than 1 git repo within a workspace.

As always if there is any extra context I can give, please get in touch with me I will be more than happy to provide it if it helps speed up the finding and fixing of this bug.

**Comment by ichim-david** [comment] 2024-08-30 08:51
![git-commit-cody](https://github.com/user-attachments/assets/d6049130-9024-426f-b15b-061ff0a17635)
I'm going to see how helpful s0 was in finding the culprit of the git commit message and which solution wins from claude 3.5 or gemini pro :)
Will be a good litmus test on how good are the docs for cody to get started with developing the vs code extension

**Comment by ichim-david** [comment] 2024-08-30 10:46
@abeatrix I noticed that you are the one who added this feature in https://github.com/sourcegraph/cody/pull/4130.
I got the commit message to work with the following changes:
https://github.com/sourcegraph/cody/blob/main/vscode/src/commands/scm/source-control.ts#L75
Replaced with:
        const currentWorkspaceUri = scm?.rootUri || vscode.workspace.workspaceFolders?.[0]?.uri;
and:
https://github.com/sourcegraph/cody/blob/main/vscode/src/commands/context/git-api.ts#L79
                if (p.uri) {
                    return p;
                }
I don't understand this diff thing, what I know is that we do get uri's and we can use it without this diffing that returns nothing otherwise.
Unfortunately I tried to debug it for too long (& too many times) and now I got banned :(
Generate commit message failed: Sourcegraph Cody Gateway: unexpected status code 403: {"error":"Cody Gateway access not enabled"}

**Comment by abeatrix** [comment] 2024-08-30 15:27
Hey @ichim-david thanks for the ping and for debugging this issue 🙇‍♀️  

I'm currently on PTO but will look into first thing when I'm back on Tuesday! 

If you can share your email on your Cody account with us, I can try to ask the team to unblock you. 
Cc @jdorfman

**Comment by jdorfman** [comment] 2024-08-30 15:30
Thanks @abeatrix 

@ichim-david I will add this to my calendar and make sure it gets addressed. Going to echo Beatrix, thanks so much for the ping and debugging, it will get it fixed faster!

**Comment by ichim-david** [comment] 2024-08-30 15:32
> Hey @ichim-david thanks for the ping and for debugging this issue 🙇‍♀️
> 
> I'm currently on PTO but will look into first thing when I'm back on Tuesday!
> 
> If you can share your email on your Cody account with us, I can try to ask the team to unblock you. Cc @jdorfman

@abeatrix no problem, now that I know how to build my cody version I can keep it until fixed.
@jdorfman luckily it was a temporary ban so no need to for unblock sorry about this noise.

**Comment by jdorfman** [comment] 2024-08-30 15:44
@ichim-david don't be sorry!

**Comment by ichim-david** [comment] 2024-08-30 15:49
> @ichim-david don't be sorry!
@jdorfman a useful feature request from my part would be to get a notice if I've made too many requests that I  will be blocked for x minutes if I get close to the limit. This way we can adapt and ensure we don't reach that status. Think even claude style you have x more messages until y time if it's done in a quick succession.

**Comment by jdorfman** [comment] 2024-09-02 18:01
@ichim-david great idea. I will make sure the product team sees this in the weekly community feedback report (which goes out tomorrow).

**Comment by ichim-david** [comment] 2024-09-05 19:08
@abeatrix your recent pull request https://github.com/sourcegraph/cody/commit/d92dcb652a5263b9737bd22e134a3feba6916bcf hasn't fixed my issue so please don't close this issue.
I suspect it still doesn't like the diffPath logic, but I don't have time to look at it until tomorrow.

**Comment by abeatrix** [comment] 2024-09-05 21:01
Update: @ichim-david I found the root cause, working on a fix now and it should be available in tomorrow's pre-release!

**Closed** 2024-09-06 01:56 UTC
Labels: bug, clients/vscode

**Comment by abeatrix** [comment] 2024-09-06 17:18
@ichim-david the fix is included in the latest pre-release version. Can you please give it a try and let me know if the issue persists for you?

**Comment by ichim-david** [comment] 2024-09-06 17:38
> @ichim-david the fix is included in the latest pre-release version. Can you please give it a try and let me know if the issue persists for you?

@abeatrix confirming that with the latest pre-release (v1.35.1725635741 (pre-release)) the command now works.

Stretching my luck a bit here but could you also have a look at the bug report I added today here https://github.com/sourcegraph/cody/issues/5489
I can't really use the smart apply button due to this bug and I would love to help out any way I can to get this issue solved as well.

**Comment by rokotyan** [comment] 2024-09-11 22:22
@abeatrix I'm getting the same error on the latest pre-release version in VScode. Is there anything I can do to help you debug this?

<img width="1345" alt="image" src="https://github.com/user-attachments/assets/3f5c7fe1-da47-4d05-b7ef-50feebf34641">

**Comment by Brawl345** [comment] 2024-09-19 12:40
I have the same issue on macOS Sonoma:

```
2024-09-19 14:35:10.756 [info] > git config --global commit.template [10ms]
2024-09-19 14:35:10.756 [warning] [Git][config] git config failed: Failed to execute git
2024-09-19 14:35:10.757 [info] > git config --local commit.template [12ms]
2024-09-19 14:35:10.757 [warning] [Git][config] git config failed: Failed to execute git
2024-09-19 14:35:10.769 [info] > git diff --name-status -z --diff-filter=ADMR --cached [10ms]
2024-09-19 14:35:10.770 [info] > git diff --name-status -z --diff-filter=ADMR [10ms]
2024-09-19 14:35:10.771 [info] > git log --format=%H%n%aN%n%aE%n%at%n%ct%n%P%n%D%n%B -z -n5 [10ms]
2024-09-19 14:35:10.811 [info] > git diff [40ms]
```

I use Git though nix-darwin and the binary ist at `/etc/profiles/per-user/USERNAME/bin/git` but it's in PATH and everything and it works with every other tool. Running `git config --global commit.template` through the Terminal in the directory also works (it prints out nothing since the option is not set).

**Comment by maheshveact** [comment] 2025-03-21 10:12
i am also having this issue

Version: 1.98.2
Commit: ddc367ed5c8936efe395cffeec279b04ffd7db78
Date: 2025-03-12T13:32:45.399Z
Electron: 34.2.0
ElectronBuildId: 11161602
Chromium: 132.0.6834.196
Node.js: 20.18.2
V8: 13.2.152.36-electron.0
OS: Darwin arm64 24.3.0
