### ISSUE TITLE
login problem cody with vs code extension 

### ISSUE THREAD

**Issue by john3825** [sourcegraph/cody#332] opened 2023-07-20 09:18 UTC
I  can't login cody with vs code extension. I logged in with GitHub before and it stop loggin in to cody.

**Comment by jdorfman** [comment] 2023-07-20 18:01
Hi can you provide the following:

- Operating system
- VS Code version
- Cody extension version

Also do you have the Cody App installed?

**Comment by john3825** [comment] 2023-07-23 05:07
My computer with vscode is

**OS**
```
Edition: Windows 11 Pro
Version: 22H2
Installed: ‎2022/‎10/‎21
OS Build: 22621.1992
Experience: Windows Feature Experience Pack 1000.22644.1000.0
```
**vscode:**
```
Version: 1.80.1 (user setup)
Commit: 74f6148eb9ea00507ec113ec51c489d6ffb4b771
Date: 2023-07-12T17:22:07.651Z
Electron: 22.3.14
ElectronBuildId: 21893604
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Windows_NT x64 10.0.22621
```
**extension**
```
Cody AI v0.6.1
```

**It keeps stop log in to cody server, hang for long time, and not responding.**

Tell me how to solve.

**Comment by john3825** [comment] 2023-07-23 05:53
The chat on the code editor works again by getting new access token, but not left sidebar chat. Tell me how to reveke and generate the access token again for leftside bar?

**Comment by jdorfman** [comment] 2023-07-25 20:44
Hey @john3825 

Sure thing. Go here: `https://sourcegraph.com/users/{YOUR-USER-NAME}/settings/tokens`

Then open the command pallet in VS Code > type "cody" > then choose "Cody: Sign out"

Let me know if this works or not.

<img width="714" alt="Image 2023-07-25 at 1 43 02 PM png" src="https://github.com/sourcegraph/cody/assets/398230/7feb72b4-2114-4243-be27-04e44630d5df">

**Comment by john3825** [comment] 2023-07-26 08:48
I got an error signing out.


```
Comman d`Cody: Sign Out...`: result in an error

Cannot read properties of null  (reading 'toString')
```

Maybe the extension is corrupsed or missing codes.



I added the authentication code, ```  "cody.assistantAccessToken": "access token"```, manually to VCS code User settings JSON file ```settings.json```. VS code does not understand the code because the ```Unknown Configuration Setting. No quick fix``` error. Please tell me how to set the authentication access token manually or vs code cody settings.

 

I still cannnot log in.

Please check what is wrong with the code error.

**Comment by abeatrix** [comment] 2023-07-27 00:04
@john3825 can you update the extension to 0.6.2 and reload the editor to see if that fixed the issue for you?

**Comment by john3825** [comment] 2023-07-27 06:42
I uninstalled and installed the extension again and **`Cody: Sign Out` and `Cody:Sign In`** from command in VSCode from/to **`sourcegraph.com`** account, but the left sidebar chat does not work. The text editor chat works but can not replace the editor text. 

There are still errors in the `Runtime status` of the extension:
```
Activation Event:onStartupFinished
Activation Time:707ms
Uncaught Errors (2)
Cannot read properties of null (reading 'toString')
Cannot read properties of null (reading 'toString')
```

**Comment by jdorfman** [comment] 2023-07-27 16:51
Thanks so much for the info @john3825 

Can you provide a screenshot and or recording of the left sidebar? That will help us big time.

**Comment by sqs** [comment] 2023-07-27 22:23
Closing as duplicate of https://github.com/sourcegraph/cody/issues/360 (which has some more info)

**Comment by jdorfman** [comment] 2023-07-27 22:24
Thanks @sqs

**Closed by sqs** 2023-07-27 22:23 UTC
Labels: clients/vscode, os/windows

**Comment by john3825** [comment] 2023-07-29 15:42
@jdorfman @sqs It worked with **pre-release** version. It was from the login error from the error. Thanks
