### ISSUE TITLE
Cody Generate Commit Message

### ISSUE THREAD

**Issue by malformed-c** [sourcegraph/cody#4941] opened 2024-07-19 18:30 UTC
### Version

Project IDX

### Describe the bug

When generating commit message it generates message for first repository ignoring submodules, even if I click on the Cody button

### Expected behavior

Messages for both repository and submodules

**Comment by vadi2** [comment] 2024-07-20 06:18
I think it would be more proper for the generate commit message to be on the main repository and per-repository as well, since those are separate concepts both in git and vscode's commit UI?

**Comment by malformed-c** [comment] 2024-08-09 07:20
i mean when i click Cody button on submodule repo it fills commit message for the main repo, not the one i clicked on

**Comment by ichim-david** [comment] 2024-08-30 07:39
@malformed-c this is a duplicate of https://github.com/sourcegraph/cody/issues/4863

I think there can be a bit of confusion as there are git submodules and then there are git clones
within another path from a git repo.

Regardless of the proper terminology, this is an issue that plagues you and @vadi2 as well as me
, and at this point we have to see which issue gets picked up in the eyes of the developers and in what
timeframe. If you have any extra context to add like screenshots, logs etc it might be useful to add them
as debug information.

**Comment by ichim-david** [comment] 2024-09-06 17:48
@vadi2 @malformed-c upgrade the plugin on vs code to the latest pre-release my issue regarding cody not reading the right repo because it always used the project repo path has been fixed as part of this issue https://github.com/sourcegraph/cody/issues/4863.
If you still encounter issues then let @abeatrix know here as he was able to fix the mentioned issue.

**Comment by PriNova** [comment] 2024-11-29 09:52
This issue can be closed. If the issue still remains please open a new issue with the steps to reproduce it.
Thank you

**Closed by PriNova** 2024-11-29 09:52 UTC
Labels: bug, repo/cody
