### ISSUE TITLE
Context Bug: Cody fails to retrieve CODEOWNER file

### ISSUE THREAD

**Issue by chillatom** [sourcegraph/cody#3322] opened 2024-03-06 18:02 UTC
Original Support Bug - https://sourcegraph.slack.com/archives/C02842Z6YAK/p1709250336702039
Background Discussion - https://sourcegraph.slack.com/archives/C04MSD3DP5L/p1709637172068829

IDEs - VS Code and Web

Description - When a user queries Cody and asks who the owners of a file are, Cody fails to interpret this query and retrieve the CODEOWNERs file.  Even @ mentioning the file specifically does not work as there may be file format issues.

**Comment by chillatom** [comment] 2024-03-18 15:35
Impacts Canva

**Comment by kalanchan** [comment] 2024-03-18 15:47
To split into 2 tickets, one to figure out why @ file wasn't work and the other for context retrieval issues

**Comment by dominiccooney** [comment] 2024-03-19 08:23
@kalanchan would be nice to link the issues back to this one.

The context retrieval is unsurprising because we look at the CONTENT of files, not their names. The idea of experimenting with different chunking has come up multiple times, @chillatom could you collate these?

**Comment by abeatrix** [comment] 2024-03-19 10:59
For the @ file not working, I wonder if that's because they copied and pasted the @ query instead of entering the query manually.

When entering the query and selecting the file manually via @-mentioned:
<img width="712" alt="image" src="https://github.com/sourcegraph/cody/assets/68532117/866b03ed-ae50-476f-a1e3-46e745460cba">
<img width="712" alt="image" src="https://github.com/sourcegraph/cody/assets/68532117/30b879a7-9b63-4862-bbbd-72acb190371c">


When copy and paste the same question with the same query:
<img width="712" alt="image" src="https://github.com/sourcegraph/cody/assets/68532117/bd9caafe-9477-405d-b853-92080ec9f8da">

Can we ask the customer to try entering the @ query manually to confirm if this is the case?

**Comment by sqs** [comment] 2024-03-19 22:16
This will now be a @jtibshirani and search platform concern - it falls within or very close to `the end-to-end user experience for factual code understanding Q&A in Cody chat (single-turn initially, and both local and remote code)`

**Comment by jtibshirani** [comment] 2024-03-20 16:50
Ack! I am putting together a set of "golden queries" for context evaluation now, which we will then use to iterate on context quality. We will make sure to include ownership queries (and other themes that we surface in https://github.com/sourcegraph/cody/issues/3321). Ideally we'd get correctly answer questions like "Who owns X file?"

In the background thread (https://sourcegraph.slack.com/archives/C04MSD3DP5L/p1709637172068829), there seems to be another issue where the customer would like to use Sourcegraph Own, but have a different format for ownership files.
@kalanchan @chillatom maybe we can dig into this and file another issue if appropriate?

**Comment by kalanchan** [comment] 2024-03-20 23:02
@abeatrix I just checked `@-file` with an owners file, and it seems to be working. 

![CleanShot 2024-03-20 at 16 01 18@2x](https://github.com/sourcegraph/cody/assets/51868853/6ad24f0d-73a6-4b92-ac4b-f4fe229dfb6f)

If someone else can confirm this behaviour works, it might just be a user error and this ticket can focus on the cody context api improvements instead

**Comment by mibali** [comment] 2024-03-22 10:30
@abeatrix I think I am able to reproduce this also

<img width="816" alt="image" src="https://github.com/sourcegraph/cody/assets/111276665/105f7420-ed9b-4377-9928-e5e48d37d471">

In the first screenshot I typed the prompt manually, while in the second screenshot I copied and pasted the @-file-name

**Comment by mibali** [comment] 2024-03-26 08:27
@abeatrix The admin confirmed that they experienced the same behavior, where the "@file"  fails to retrieve CODEOWNER files when the it is copied and pasted instead of being entered manually. Tho, he mentioned that the parser should still process the directive correctly even if copied and pasted.

**Comment by kalanchan** [comment] 2024-04-18 21:43
closing in favor of #3867

**Closed by kalanchan** 2024-04-18 21:43 UTC
Labels: context, cody
