### ISSUE TITLE
Cody might be re-opening deleted files in VS Code

### ISSUE THREAD

**Issue by beyang** [sourcegraph/cody#1050] opened 2023-09-13 17:28 UTC
From @eseliger:
>  I am not 100% sure if this is from Cody, but maybe since we keep last open files in memory somewhere and do a read call on them for context fetching?
> Since a while, I have a weird bug in vscode that sometimes files I deleted reappear as an unsaved empty file in my open editors. I can close them, and they might reappear again. Does that ring any bells at all?

* Here's where we return the last N files: https://sourcegraph.com/github.com/sourcegraph/cody/-/blob/vscode/src/completions/context/history.ts?L63-81
* And indeed we open each of these text documents: https://sourcegraph.com/github.com/sourcegraph/cody@123bbdb43b4599823e4e82210152f6491e41913c/-/blob/vscode/src/completions/context/context-local.ts?L158-167

Need to verify:
* Opening a text document through the VS Code API causes it to be added to the list of open editors in the GUI

If that's the case, we should keep track of file deletions and remove those files from the history (they also won't be considered for completions purposes, which is fine)

**Comment by philipp-spiess** [comment] 2023-11-06 10:12
Hey! I looked into this issue and can't reproduce it. @eseliger does this still happen to you? If you try to open a document that is deleted, the open method will throw and we handle this case in code by now. I don't experience any open editors to be populated again when it shouldn't :/

**Comment by eseliger** [comment] 2023-11-06 15:22
Haven't seen it recently!

**Comment by philipp-spiess** [comment] 2023-11-08 11:16
@eseliger Cool! Let me know if this is an issue again, closing in the mean time until we have a repro

**Closed by philipp-spiess** 2023-11-08 11:16 UTC
Labels: clients/vscode
