### ISSUE TITLE
Broke Cody by asking about styling a h1

### ISSUE THREAD

**Issue by jdorfman** [sourcegraph/cody#741] opened 2023-08-18 20:05 UTC
This is from a [Tweet](https://twitter.com/jdorfman/status/1692611032684880087).

I was unable to replicate it myself. Prompt:

`how do i style the h1 like it would be in prose with tailwind typography`

![image](https://github.com/sourcegraph/cody/assets/398230/2462d08e-46e5-4f1e-86d2-c85446825c0b)

**Comment by jdorfman** [comment] 2023-08-18 20:09
Unable to replicate it on my end. What I get when a css file is open or not:

<img width="435" alt="Image 2023-08-18 at 1 06 14 PM png" src="https://github.com/sourcegraph/cody/assets/398230/793fbcee-1b43-4b9f-944d-3c338d8d1038">

**Comment by abeatrix** [comment] 2023-08-18 20:30
@kalanchan has a query that can reproduce the issue: how to style an h1 with tailwind css prose?

I noticed we are allowing h tags to escape here: https://sourcegraph.com/github.com/sourcegraph/cody/-/blob/lib/shared/src/chat/markdown.ts?L20-25

@philipp-spiess would removing those h tags from the allow list cause regression issues?

**Comment by kalanchan** [comment] 2023-08-18 20:39
looks like it breaks when Cody has `h1` inside it's reponse 

![image](https://github.com/sourcegraph/cody/assets/51868853/d29e1890-55fb-4c18-bffc-53f546b47ac9)

**Comment by abeatrix** [comment] 2023-08-21 20:56
Should be fixed by https://github.com/sourcegraph/cody/pull/742 and the fix is included in the v0.8.0 release.

**Closed by abeatrix** 2023-08-21 20:56 UTC
Labels: clients/vscode
