### ISSUE TITLE
bug: Opening a chat from history shows timestamp in tab title instead of chat title

### ISSUE THREAD

**Issue by toolmantim** [sourcegraph/cody#2303] opened 2023-12-12 13:07 UTC
### Version

0.18.0

### Describe the bug

When loading up an existing conversation, instead of the tab title it shows a timestamp:

<img width="1094" alt="Screenshot 2023-12-13 at 12 04 28 am" src="https://github.com/sourcegraph/cody/assets/153/ce29d5c1-808e-4a48-8a26-9d7c6f470884">

To reproduce:
* Start a chat
* Type a message
* Note the tab title
* Close the chat
* Reopen the chat
* Note the tab title is now a timestamp

### Expected behavior

Tab title shows the chat title

**Comment by toolmantim** [comment] 2023-12-12 13:07
@deepak2431 might this be related to the chat rename PR?

**Comment by deepak2431** [comment] 2023-12-12 13:09
@toolmantim I think this is introduced due to some other PRs, cuz before my PR got merged, it was in the `main` branch I saw. But let me look into it and spin up a PR for the fix.

**Comment by taylorsperry** [comment] 2023-12-12 15:21
Closing as this is a dupe of https://github.com/sourcegraph/cody/issues/2260. @deepak2431 would you please reference that issue if you're able to push a fix? Thank you!

**Closed by taylorsperry** 2023-12-12 15:21 UTC
Labels: bug, clients/vscode
