### ISSUE TITLE
bug: screen turned all grey

### ISSUE THREAD

**Issue by RawnerveOh** [sourcegraph/cody#5769] opened 2024-10-01 14:33 UTC
Type: <b>Bug</b>

## Extension Information

- Cody Version: 1.34.3
- VS Code Version: 1.93.1
- Extension Host: desktop

##  Steps to Reproduce

1.
2.
3.

## Logs

Extension version: 1.34.3
VS Code version: Code 1.93.1 (38c31bc77e0dd6ae88a4e9cc93428cc27a56ba40, 2024-09-11T17:20:05.685Z)
OS version: Linux x64 6.8.0-45-generic
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 1700 Eight-Core Processor (16 x 3742)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off<br>webnn: disabled_off|
|Load (avg)|1, 1, 1|
|Memory (System)|62.72GB (48.93GB free)|
|Process Argv|--ms-enable-electron-run-as-node --extensions-dir=/home/wheels/.var/app/com.visualstudio.code/data/vscode/extensions --reuse-window --crash-reporter-id 1fd6af93-c21e-48a0-82cc-04a2e2d0463b|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|zorin|
|XDG_CURRENT_DESKTOP|zorin:GNOME|
|XDG_SESSION_DESKTOP|zorin|
|XDG_SESSION_TYPE|x11|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805cf:30301675
binariesv615:30325510
vsaa593:30376534
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
a9j8j154:30646983
962ge761:30959799
pythongtdpath:30769146
welcomedialog:30910333
pythonnoceb:30805159
asynctok:30898717
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
accentitlementsc:30995553
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
9c06g630:31013171
a69g1124:31058053
dvdeprecation:31068756
dwnewjupyter:31046869
newcmakeconfigv2:31071590
impr_priority:31102340
nativerepl1:31139838
refactort:31108082
pythonrstrctxt:31112756
flighttreat:31134774
wkspc-onlycs-t:31132770
nativeloc2:31134642
wkspc-ranged-c:31125598
cf971741:31144450
defaultse:31146405
iacca1:31144502
5fd0e150:31146321

```

</details>

**Comment by sqs** [comment] 2024-10-03 09:04
What were you doing when it turned gray? This is usually an out of memory error caused by a memory leak.

**Comment by theronburger** [comment] 2024-10-08 08:55
This is a dupe of https://github.com/sourcegraph/cody/issues/5296
I provide possible reasons here. spoiler alert, cody spams state hard and crashes it

**Comment by PriNova** [comment] 2024-11-21 20:57
This issue is already resolved and will be closed.

**Closed by PriNova** 2024-11-21 20:57 UTC
Labels: bug, repo/cody
