### ISSUE TITLE
bug: Chat hangs when the current open tab contains a new unsaved file

### ISSUE THREAD

**Issue by chwarwick** [sourcegraph/cody#1989] opened 2023-11-29 14:53 UTC
### Version

v0.16.1

### Describe the bug

When starting a new chat if the current file is a new unsaved file, chat hangs indefinitely and can not be canceled. Tested in the current and experimental chat interface.

To reproduce:

1. Cmd-N to open a new unsaved file
2. In the Cody Chat - Ask a question

Debug output suggests that it is stuck trying to gather context as I don't see logging of an outgoing request.  

### Expected behavior

Chat should return with a response and be cancelable

### Additional context

https://github.com/sourcegraph/cody/assets/6098507/ef64ee56-a20c-4f29-b59d-2927750add40

**Comment by abeatrix** [comment] 2023-11-30 20:03
@chwarwick I think this is fixed in the latest insider build, can you give that a try and let me know if the issue persists?

From my testing, chat works with untitled file:

![image](https://github.com/sourcegraph/cody/assets/68532117/69ce076b-fbe0-4c10-8993-a10bde447422)

chat also works with no file opened: 

![image](https://github.com/sourcegraph/cody/assets/68532117/d1bb3d98-f8a3-4b75-b964-a5606418b218)

**Comment by chwarwick** [comment] 2023-11-30 21:33
> @chwarwick I think this is fixed in the latest insider build, can you give that a try and let me know if the issue persists?

I was still able to reproduce the issue, I think the reason it's working for you is that some of the context methods don't appear to kick in for very basic chats like `hey, hello, etc...`

Some additional details it will work for me if I first say "Hi" it responds and then I ask a follow up like "what does this repo do?"

https://github.com/sourcegraph/cody/assets/6098507/4d970ae3-7ba0-4928-aed5-8b2492e73c2c

**Comment by abeatrix** [comment] 2023-12-01 05:38
@chwarwick i tried it with the same question on both new chat UI and old chat UI and still couldn't reproduce the issue 🤔 

https://github.com/sourcegraph/cody/assets/68532117/424060bb-48e9-4cdf-beeb-75c0f9b9d438

https://github.com/sourcegraph/cody/assets/68532117/676b3f0c-30db-48d7-a144-6c86e75fe345

Which instance are you connected to?

**Comment by chwarwick** [comment] 2023-12-01 12:12
> Which instance are you connected to?

s2

**Comment by abeatrix** [comment] 2023-12-04 21:54
i tried connecting to s2 and still not able to reproduce the issue 😓 

<img width="1555" alt="image" src="https://github.com/sourcegraph/cody/assets/68532117/a15eccc4-059c-43dc-9d0f-af5468d9ddde">

@kalanchan can you give it a try and let me know if this is an issue for you as well?

**Comment by taylorsperry** [comment] 2023-12-06 21:31
I can't repro this either (I'm on the pre-release with New Chat UX disabled). Marking P2 for now.

**Closed** 2024-01-02 16:29 UTC
Labels: bug, clients/vscode
