### ISSUE TITLE
bug: cody creates unsved files keep showing back after closing

### ISSUE THREAD

**Issue by watevadafa** [sourcegraph/cody#4581] opened 2024-06-17 08:41 UTC
### Version

1.90.0

### Describe the bug

Version: 1.90.0
Commit: 89de5a8d4d6205e5b11647eb6a74844ca23d2573
Date: 2024-06-04T19:34:48.028Z
Electron: 29.4.0
ElectronBuildId: 9593362
Chromium: 122.0.6261.156
Node.js: 20.9.0
V8: 12.2.281.27-electron.0
OS: Darwin arm64 23.5.0

When cody creates files say, test-something.py or any untitled.py, these files if ignored and closed keep showing up after sometime 

### Expected behavior

Once closed it should be closed, or ignored when user opt-out saving them!

**Comment by waldyrious** [comment] 2024-06-28 11:13
I've also been experiencing this, and it's so frustrating that I had to disable the extension. What's most annoying is that the files are empty, with no undo history, yet I can't even close them without getting the dialog about losing unsaved changes.

**Comment by felixfbecker** [comment] 2024-06-28 18:05
I am also seeing this since last week or so, I didn't realize it was caused by the Cody extension!

**Comment by recurser** [comment] 2024-07-02 03:18
Same issue for the last couple of weeks. I've had to disable the extension because of it.

**Comment by deadband** [comment] 2024-07-03 02:36
I am experiencing the same issue with Cody AI. Anytime a file is modified a new untitled file will be created. Apparently, there is a very similar issue with [here Github Copilot](https://github.com/sourcegraph/cody/issues/4581).

**Comment by JeongJuhyeon** [comment] 2024-07-05 09:47
I've also been experiencing this, and through "Extension Bisect" confirmed that it only happens with Cody on.

@deadband Currently, your link goes to this issue itself.

**Comment by justinmilner1** [comment] 2024-07-08 15:19
I'm having trouble replicating this - Are any of you aware of a consistent method leading to this behavior?

It appears the only pathway which _should_ create new files is the 'Generate Unit Tests' command - have you been utilizing this command? 
If not, do you use any other commands?

**Comment by JeongJuhyeon** [comment] 2024-07-08 18:50
@justinmilner1 

I've even recorded my screen to watch when the files suddenly get opened. 
It's difficult to pinpoint, but it looks related to one or more of the following

- Having had a Chat with Cody in the current session, or at least having a Chat open somewhere in the workspace. I think this is a prerequisite for this to happen.
- Possibly, having mentioned (@) a workspace file in the Chat, or currently being in the process of doing so.
- Saving (or autosaving) of modified code files
- Focus switching to another split view (or possibly just to another tab)

FWIW I've never used the "Generate Unit Tests" command, and the video I took shows it does not happen upon the user directly interacting with Cody.

**Comment by justinmilner1** [comment] 2024-07-08 20:06
@JeongJuhyeon Got it, thanks for the info. Do you mind sharing the video?

**Comment by JeongJuhyeon** [comment] 2024-07-08 20:20
> @JeongJuhyeon Got it, thanks for the info. Do you mind sharing the video?

Unfortunately that's not easy because I spend most of my time writing closed source code, and as such I've already deleted it. Happy to assist with other kinds of debugging if possible.

**Comment by justinmilner1** [comment] 2024-07-08 22:10
@JeongJuhyeon Ah gotcha.
Two more questions:
- Are the unexpected files always untitled and empty for you? 
- Does this happen often? Or only occasionally?

I believe the issue is likely inadvertant calls of [openUntitledDocument](https://github.com/sourcegraph/cody/blob/f638a27248424b881904ca0a0d98bf347d2fc34f/agent/src/vscode-shim.ts#L496), but there are a lot of reasons that could be happening.
Created [this pr](https://github.com/sourcegraph/cody/pull/4810) to maybe get some more info.

**Comment by JeongJuhyeon** [comment] 2024-07-09 07:32
@justinmilner1 

> Are the unexpected files always untitled and empty for you?

Yes, they are always untitled and empty.

>Does this happen often? Or only occasionally?

It seems to get worse the more I use chat (or possibly the more chat windows I have open, or the more files I have @ mentioned in chat) in a given session. When I've used chat quite a bit it can be pretty bad, with a good number of new files having opened after an hour of coding. For me it's often enough that the distraction of having to close random files makes me disable Cody, despite finding it a much better product than competitors' offerings.

What I'll try and do is have the Cody extension activated but not use any of its functionality, and see if it still happens. So far it looks like it won't.

**Comment by worm2fed** [comment] 2024-07-10 08:19
For me this happening even If I do not open a chat
Also seems related - I might create an empty file and make some drafts and later - close this file, and after that Cody will create empty files.

**Comment by JeongJuhyeon** [comment] 2024-07-10 08:37
> For me this happening even If I do not open a chat Also seems related - I might create an empty file and make some drafts and later - close this file, and after that Cody will create empty files.

This could very well be related - I also often open empty files, make drafts and then close them.

**Comment by c0dification** [comment] 2024-07-10 21:44
I disabled the extension, switched to `Release version` in the config, restarted VS Code, and re-enabled the extension. I haven't had the issue and it's been a full day of use with many new and existing files. Maybe related to pre-release version?

**Comment by c0dification** [comment] 2024-07-11 20:38
nope. it's started again for me. i have not used cody chat or any other features except the code completion suggestions.

**Comment by JeongJuhyeon** [comment] 2024-07-12 04:41
> nope. it's started again for me. i have not used cody chat or any other features except the code completion suggestions.

Do you also have a habit of sometimes creating empty files (e.g. to paste stuff into, or to make a draft) and then closing them, like @worm2fed and me?

**Comment by felixfbecker** [comment] 2024-07-12 05:07
I might be misremembering but I also think every time I had this issue, I had made some untitled files to paste some stuff into. I think I close them eventually or restart VS Code or something and start noticing how there would still be "untitled" files popping up.

**Comment by worm2fed** [comment] 2024-07-12 07:05
Maybe Cody trying to be smart and learning on such behavior (create files for smth)?

**Comment by worm2fed** [comment] 2024-07-16 16:25
It's getting worse, now it creates a new file immediately after I close it.

It put's two log messages into output window. First when I'm clicking close on file, and second one when it creates a new file again
```
█ SimpleChatPanelProvider: postContextStatus [{"displayName":"project","providers":[{"kind":"embeddings","state":"ready","embeddingsAPIProvider":"sourcegraph"},{"kind":"search","type":"local","state":"ready"}]}]
█ SimpleChatPanelProvider: postContextStatus [{"displayName":"project","providers":[{"kind":"embeddings","state":"ready","embeddingsAPIProvider":"sourcegraph"},{"kind":"search","type":"local","state":"ready"}]}]
```

**Comment by abs-angularminds** [comment] 2024-07-16 17:16
> Maybe Cody trying to be smart and learning on such behavior (create files for smth)?

No, it is creating untitled files at the root location. These files are not like regular new files that we can easily close. When prompted to save, it asks for confirmation. What should someone do by saving these files?

**Comment by abs-angularminds** [comment] 2024-07-16 17:18
> It's getting worse, now it creates a new file immediately after I close it.
> 
> It put's two log messages into output window. First when I'm clicking close on file, and second one when it creates a new file again
> 
> ```
> █ SimpleChatPanelProvider: postContextStatus [{"displayName":"project","providers":[{"kind":"embeddings","state":"ready","embeddingsAPIProvider":"sourcegraph"},{"kind":"search","type":"local","state":"ready"}]}]
> █ SimpleChatPanelProvider: postContextStatus [{"displayName":"project","providers":[{"kind":"embeddings","state":"ready","embeddingsAPIProvider":"sourcegraph"},{"kind":"search","type":"local","state":"ready"}]}]
> ```

This is indeed becoming worse. I have disabled the extension. It was creating multiple files. Started with creating one, then kept on increasing 5-6 files. And it won't let me close. Opens more as soon as I close one.

**Comment by JeongJuhyeon** [comment] 2024-07-16 18:22
@worm2fed @abs-angularminds It seems like not leaving any more unsaved files open has fixed it for me. I now just keep a separate VSCode window open to paste/draft random stuff when I want to.

**Comment by sbuttgereit** [comment] 2024-07-16 19:29
I'm seeing this as well.  I made a video where I see this with a project that I'm working on.  Before the video, I closed all tabs and then exited so that the next launch would have no files open.  Then I open a file and unwanted tabs are opened next.  Next steps are not in the video, I close the unwanted tabs and answer the prompt "do I want to save?" : "no".  As soon as I finish answering the last modal yes/no prompt, new tabs open up.


https://github.com/user-attachments/assets/be1b0a57-e266-417e-a2ec-e08ea1eec018

In this case then, the only thing I did in the session was select a file in the file browser and then close the unwanted tabs.  The one complication is that I'm connecting to a WSL session.

The version of the VS Code extension I made the video with is: 
![image](https://github.com/user-attachments/assets/bde7a46a-cc50-4817-9755-1d7cf014f91b)

Though I have been experiencing this prior to updating.

**Comment by caspark** [comment] 2024-07-18 01:57
I am also having this issue of untitled tabs being created/sticking around.

## Recording

* 64-second demo of it on a fresh, near-empty repo
* no user settings, except pre-authenticating with cody and accepting at least 1 auto-complete suggestion in the past (from previous takes)
* vscode window was opened just before starting recording, with all extensions disabled (you do see me disable them at the start of the video, but FYI they were already all disabled when I opened that vscode window)
* recorded on VSCode v1.89.1 on Linux

[Screencast_20240718_093718.webm](https://github.com/user-attachments/assets/47192c47-990b-423f-b695-e22d44783296)

Here's a proper bug report with repro steps etc (note these steps are slightly different from what's visible in my text editor in the video - I couldn't be bothered doing another take):

## Repro steps

0. Disable all installed extensions (does not seem to be strictly necessary for me, but I include this to show it's not an interaction with another third party extension)
1. Create a new workspace with a `main.py` in it
2. Press <kbd>Ctrl+N</kbd> to create a new untitled tab
3. Close the untitled tab, and notice that it stays closed as expected
4. Enable Cody
5. Press <kbd>Ctrl+N</kbd> to create a new untitled tab
6. Close the untitled tab, and notice that it stays closed
7. Type something in the `main.py` file to trigger an inline autocomplete suggestion (no need to accept it)
8. Press <kbd>Ctrl+N</kbd> to create a new untitled tab
9. Close the untitled tab

## Observed

The untitled tab gets auto-reopened each time it's closed, and attempting to close the re-opened tab prompts to save its contents.

## Expected

The untitled tab should stay closed.

## Workaround

To remove "stuck open" untitled tabs:

1. Disable Cody extension
2. Restarting extensions as prompted by vscode
3. Close all open untitled (i.e. unsaved new file) tabs
4. Re-enable Cody extension

Then avoid ever creating any new untitled tabs, otherwise the issue will recur.

## Other notes

* No need to type anything into the untitled tab
* You can end up with lots of unclosable untitled tabs if you open lots manually
* I can reproduce this after nuking my personal settings in ~/.config/Code too, so it's unlikely to be a VSCode setting I've changed
* Obviously this is unrelated to the "chat" feature - it's triggerable purely via autocomplete, and I'm pretty sure you don't even need to accept the autocomplete.
    * I'd guess that it's probably caused by the autocomplete's context gathering looking at recent edit locations (or cursor positions?), and somehow that is mutating the undo history of the text buffers, which causes vscode to reopen those tabs? That's total speculation though.

And yes, it is super annoying.

**Closed** 2024-07-19 19:00 UTC
Labels: bug, clients/vscode
