### ISSUE TITLE
bug: THe Cody chat window panel shows nothing but a gray background.

### ISSUE THREAD

**Issue by OCIO-ricky** [sourcegraph/cody#5296] opened 2024-08-22 15:15 UTC
Type: <b>Bug</b>

## Extension Information

- Cody Version: 1.32.0
- VS Code Version: 1.92.2
- Extension Host: desktop

##  Steps to Reproduce

1.
2.
3.

## Logs

Extension version: 1.32.0
VS Code version: Code 1.92.2 (fee1edb8d6d72a0ddff41e5f71a671c23ed924b9, 2024-08-14T17:29:30.058Z)
OS version: Windows_NT x64 10.0.22631
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz (8 x 2592)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|undefined|
|Memory (System)|31.83GB (16.24GB free)|
|Process Argv|--crash-reporter-id 0cd76725-8175-4795-9208-d6bca1b6fc07|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
vscod805cf:30301675
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
pythongtdpath:30769146
welcomedialog:30910333
pythonnoceb:30805159
asynctok:30898717
pythonregdiag2:30936856
pythonmypyd1:30879173
2e7ec940:31000449
pythontbext0:30879054
accentitlementsc:30995553
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
bdiig495:31013172
pythoncenvpt:31062603
a69g1124:31058053
dvdeprecation:31068756
dwnewjupyter:31046869
newcmakeconfigv2:31071590
impr_priority:31102340
refactort:31108082
pythonrstrctxt:31112756
flighttreat:31119336
wkspc-onlycs-c:31111717
wkspc-ranged-c:31118571
ei213698:31121563

```

</details>

**Comment by AlfSandoval** [comment] 2024-08-23 00:51
Same here. Happens in every chat - chat length is variable. Have to open new chat and navigate back to original to recover. 

V1.32.0

**Comment by awesomebytes** [comment] 2024-08-23 17:22
Same here.

**Comment by theronburger** [comment] 2024-09-30 10:32
Same here
Closing https://github.com/sourcegraph/cody/issues/5752 in favour of this 

Note, if you wait for the stream to finish in the output and restart VSCode, the chat is present completed in history. 
I would assume there is something unhandled in the UI during streaming

**Comment by theronburger** [comment] 2024-10-02 13:21
To add more context, it seems like you guys are spamming the state HARD

2000 odd `console.ts:137 [Extension Host] Dropping extra events.` coming from cody white streaming, then 
`console.ts:137 [Extension Host] Dropping extra events.` just before the crash

<img width="1464" alt="Screenshot 2024-10-02 at 15 20 19" src="https://github.com/user-attachments/assets/2738f118-ccfd-4462-8bb1-52eaf7838b4d">

**Comment by dominiccooney** [comment] 2024-10-09 11:07
@theronburger thanks for that screenshot.

"Dropping extra events" comes from the Telemetry system. Yes, then number seems excessive but I think that is a symptom not a cause.

The "URI Malformed" exception is interesting.

**Comment by dominiccooney** [comment] 2024-10-09 13:51
I have not been able to reproduce this, but I have a loose theory about what is going on.

On the extension side, we spam onMessage event registration and disposal a lot with observables, for example:

```
█ [RPC]: W->X: [{"streamId":"v7vkz2bnm21vtvk9","method":"evaluatedFeatureFlag","args":["cody-experimental-one-box"]}]
█ [RPC]: X->W: [{"streamId":"v7vkz2bnm21vtvk9","streamEvent":"next","data":false}]
```

Each observation is a new message handler. It is not clear to me yet when these are cleaned up. Possibly we send a lot of the same message for a while.

VSCode spends a lot of time decoding these messages in this chatty protocol, we might spend 20% of our time doing this VSCode-level RPC protocol to pump the messages to the webview.

![image](https://github.com/user-attachments/assets/6cc0b77e-a549-4ab9-9c49-fa7dda49456d)

Separately, other times we skip frames in VSCode itself because it chokes on our extension state:

![image](https://github.com/user-attachments/assets/290030f9-b7bb-4396-a3c0-b4b7421a4046)

**Comment by PriNova** [comment] 2024-11-21 20:59
This issue is already resolved and will be closed.

**Closed by PriNova** 2024-11-21 20:59 UTC
Labels: bug, repo/cody
