### ISSUE TITLE
bug: The grey screen of death is back.

### ISSUE THREAD

**Issue by tech-and-ai** [sourcegraph/cody#5529] opened 2024-09-10 11:39 UTC
Type: <b>Bug</b>

## Extension Information

- Cody Version: 1.35.1725895005
- VS Code Version: 1.93.0
- Extension Host: desktop

##  Steps to Reproduce

1. I simply asked a couple of prompts and it happend three times in a row.
2.
3.

## Expected Behaviour

1) Cody usually replies. 

## Logs

Extension version: 1.35.1725895005
VS Code version: Code 1.93.0 (Universal) (4849ca9bdf9666755eb463db297b69e5385090e3, 2024-09-04T13:02:38.431Z)
OS version: Darwin arm64 23.2.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M2 (8 x 2400)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|2, 3, 2|
|Memory (System)|8.00GB (0.06GB free)|
|Process Argv|--crash-reporter-id 97ffa969-f98b-4351-a114-1c082c80cb86|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805:30301674
binariesv615:30325510
vsaa593:30376534
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
pythongtdpath:30769146
welcomedialogc:30910334
pythonnoceb:30805159
asynctok:30898717
pythonregdiag2:30936856
pythonmypyd1:30879173
2e7ec940:31000449
pythontbext0:30879054
accentitlementst:30995554
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
da93g388:31013173
a69g1124:31058053
dvdeprecation:31068756
dwnewjupyter:31046869
newcmakeconfigv2:31071590
impr_priority:31102340
refactort:31108082
pythonrstrctxt:31112756
wkspc-onlycs-t:31111718
wkspc-ranged-c:31125598
fje88620:31121564
aajjf12562:31125793

```

</details>

**Comment by theronburger** [comment] 2024-10-08 08:59
Is this a dupe of https://github.com/sourcegraph/cody/issues/5296?
I provide possible reasons here. spoiler alert, cody spams state hard and crashes it 
Recover the chat by restarting and going to history. 
Come on SourceGraph, fix this, its a huge pain

**Comment by PriNova** [comment] 2024-11-21 20:56
This issue is already resolved and will be closed.

**Closed by PriNova** 2024-11-21 20:56 UTC
Labels: bug, repo/cody
