### ISSUE TITLE
Bug: Autocomplete runs in files that should be ignored by ./cody/ignore

### ISSUE THREAD

**Issue by cbart** [sourcegraph/cody#2976] opened 2024-01-30 14:22 UTC
v1.2.1

**Steps to reproduce**
Enabled unstable setting
Ignored all .go files with **/*.go
reloaded vs code
Opened an existing go file and pressed entering after a line of code

Actual:
Got an autocomplete

Expected:
No autocomplete should be run or returned.

**Comment by chwarwick** [comment] 2024-03-07 14:27
duplicate of https://github.com/sourcegraph/cody/issues/3035

**Closed by chwarwick** 2024-03-07 14:27 UTC
