### ISSUE TITLE
Blacklist files from context window

### ISSUE THREAD

**Issue by malomarrec** [sourcegraph/cody#227] opened 2023-04-07 08:09 UTC
#### Problem

The team at https://github.com/sourcegraph/accounts/issues/8674 wants the ability to blacklist certain files from ever being read into the context window. 
That's because they have highly valuable files that they don't want to be sent out of their network.

#### Proposal

- Add a .codyignore file mechanism?

#### Impacted customers

- https://github.com/sourcegraph/accounts/issues/8674

**Comment by beyang** [comment] 2023-12-18 06:33
Dupe of https://github.com/sourcegraph/cody/issues/1049

**Closed by beyang** 2023-12-18 06:33 UTC
Labels: filters, feature-request
