### ISSUE TITLE
Bug: Warning: Ignored prior context items due to context limit when using VSCode extension

### ISSUE THREAD

**Issue by art-divin** [sourcegraph/cody#2352] opened 2023-12-13 20:51 UTC
### Version

0.18.5

### Describe the bug

When I use Cody VSCode extension
With a local copy of the Swift Compiler repository
And I use chat sending 5-6 messages
Then I see the error "Warning: Ignored prior context items due to context limit"

### Expected behavior

I should not see the error, and the chat should work as one would expect

### Additional context

Here's the log from Console output in VSCode:
```
█ logEvent: CodyVSCodeExtension:CodySavedLogin:executed VSCode {"opts":{"hasV2Event":true}}
█ telemetry-v2: recordEvent: cody.extension/savedLogin: {"parameters":{"version":0,"metadata":[{"key":"contextSelection","value":1},{"key":"chatPredictions","value":0},{"key":"guardrails","value":0}]}}
█ CommandsController:fileWatcherInit: watchers created
█ AuthProvider:init:lastEndpoint: https://sourcegraph.com/
█ LocalEmbeddingsController: constructor
█ CodyEngine: using downloaded path "/Users/<#user#>/Library/Application Support/Code/User/globalStorage/sourcegraph.cody-ai/cody-engine/cody-engine-5.2.11763-macos-arm64"
█ LocalEmbeddingsController: spawnAndBindService service started, initializing
█ LocalEmbeddingsController: spawnAndBindService index library paths {"indexPath":"/Users/<#user#>/Library/Caches/com.sourcegraph.cody/embeddings","appIndexPath":"/Users/<#user#>/Library/Caches/com.sourcegraph.cody/blobstore/buckets/embeddings"}
█ CodyEngine: stderr Starting main loop. VERBOSE_DEBUG=false

█ CodyEngine: stderr github.com/<#user#>/swift: 
█ CodyEngine: stderr "
█ CodyEngine: stderr /Users/<#user#>/Library/Caches/com.sourcegraph.cody/embeddings/.tmp2xwEkP"

█ LocalEmbeddingsController: spawnAndBindService initialized [object Object] token available? true
█ ChatManager:constructor: init has local embeddings controller
█ ChatPanelsManager:constructor: init
█ main:deserializeWebviewPanel: reviving last unclosed chat panel
█ ChatPanelsManager:createWebviewPanel: 0
█ LocalEmbeddingsController: start
█ LocalEmbeddingsController: get status
█ SimpleChatPanelProvider: postContextStatusToWebView [{"name":"/Users/<#user#>/Documents/Projects/swift","providers":[{"kind":"embeddings","type":"local","state":"ready"}]}]
█ SimpleChatPanelProvider:revive: registering webview panel
█ SimpleChatPanelProvider:registerWebviewPanel: registering webview panel
█ symf: using downloaded symf "/Users/<#user#>/Library/Application Support/Code/User/globalStorage/sourcegraph.cody-ai/symf/symf-v0.0.2-aarch64-macos"
█ LocalEmbeddingsController: get status
█ SimpleChatPanelProvider: postContextStatusToWebView [{"name":"/Users/<#user#>/Documents/Projects/swift","providers":[{"kind":"embeddings","type":"local","state":"ready"}]}]
█ Cody:publishConfig: configForWebview 
█ ContextProvider:onConfigurationChange: using codebase 
█ logEvent: CodyVSCodeExtension:Auth:connected VSCode {"opts":{"agent":true}}
█ telemetry-v2: recordEvent: cody.auth/connected: {"parameters":{"version":0,"metadata":[{"key":"contextSelection","value":1},{"key":"chatPredictions","value":0},{"key":"guardrails","value":0}]}}
█ symf: creating index /Users/<#user#>/Library/Application Support/Code/User/globalStorage/sourcegraph.cody-ai/symf/indexroot/Users/<#user#>/Documents/Projects/swift
█ SimpleChatPanelProvider: postContextStatusToWebView [{"name":"/Users/<#user#>/Documents/Projects/swift","providers":[{"kind":"embeddings","type":"local","state":"ready"}]}]
█ SimpleChatPanelProvider:onDidReceiveMessage: initialized
█ SimpleChatPanelProvider: updateViewConfig 
█ CodyCompletionProvider:initialized: fireworks/starcoder-hybrid
█ SimpleChatPanelProvider: postContextStatusToWebView [{"name":"/Users/<#user#>/Documents/Projects/swift","providers":[{"kind":"embeddings","type":"local","state":"ready"}]}]
█ SimpleChatPanelProvider: getEnhancedContext > embeddings (start)
█ SimpleChatPanelProvider: getEnhancedContext > searching local embeddings
█ LocalEmbeddingsController: returning 15 results
█ SimpleChatPanelProvider: getEnhancedContext > embeddings (end)
█ DefaultPrompter.makePrompt: Ignored 1 additional context items due to limit reached
█ logEvent: CodyVSCodeExtension:recipe:chat-question:executed VSCode {"properties":{"requestID":"b7616ef9-9bdd-4959-bc40-54d89b606dfc","chatModel":"anthropic/claude-2.0","promptText":"hello","contextSummary":{"embeddings":15}},"opts":{"hasV2Event":true}}
█ telemetry-v2: recordEvent: cody.recipe.chat-question/executed: {"parameters":{"version":0,"metadata":[{"key":"embeddings","value":15},{"key":"contextSelection","value":1},{"key":"chatPredictions","value":0},{"key":"guardrails","value":0}]}}
█ main:deserializeWebviewPanel: reviving last unclosed chat panel
█ ChatPanelsManager:createWebviewPanel: 1
█ LocalEmbeddingsController: start
█ LocalEmbeddingsController: get status
█ SimpleChatPanelProvider: postContextStatusToWebView [{"name":"/Users/<#user#>/Documents/Projects/swift","providers":[{"kind":"embeddings","type":"local","state":"ready"}]}]
█ SimpleChatPanelProvider:revive: registering webview panel
█ SimpleChatPanelProvider:registerWebviewPanel: registering webview panel
█ LocalEmbeddingsController: get status
█ SimpleChatPanelProvider: postContextStatusToWebView [{"name":"/Users/<#user#>/Documents/Projects/swift","providers":[{"kind":"embeddings","type":"local","state":"ready"}]}]
█ LocalEmbeddingsController: get status
█ SimpleChatPanelProvider: postContextStatusToWebView [{"name":"/Users/<#user#>/Documents/Projects/swift","providers":[{"kind":"embeddings","type":"local","state":"ready"}]}]
█ SimpleChatPanelProvider: postContextStatusToWebView [{"name":"/Users/<#user#>/Documents/Projects/swift","providers":[{"kind":"embeddings","type":"local","state":"ready"}]}]
█ SimpleChatPanelProvider:onDidReceiveMessage: initialized
█ SimpleChatPanelProvider: updateViewConfig 
█ SimpleChatPanelProvider: postContextStatusToWebView [{"name":"/Users/<#user#>/Documents/Projects/swift","providers":[{"kind":"embeddings","type":"local","state":"ready"}]}]
█ logEvent: CodyVSCodeExtension:recipe:chat-question:executed VSCode {"properties":{"requestID":"716b3ed3-7d58-4dd5-8487-e384a134c189","chatModel":"anthropic/claude-2.0","promptText":"hi","contextSummary":{}},"opts":{"hasV2Event":true}}
█ telemetry-v2: recordEvent: cody.recipe.chat-question/executed: {"parameters":{"version":0,"metadata":[{"key":"contextSelection","value":1},{"key":"chatPredictions","value":0},{"key":"guardrails","value":0}]}}
█ logEvent: CodyVSCodeExtension:recipe:chat-question:executed VSCode {"properties":{"requestID":"d0d7f9c9-c7ce-4caa-86c5-12f8a38e435d","chatModel":"anthropic/claude-2.0","promptText":"what's the meaning of life and everything","contextSummary":{}},"opts":{"hasV2Event":true}}
█ telemetry-v2: recordEvent: cody.recipe.chat-question/executed: {"parameters":{"version":0,"metadata":[{"key":"contextSelection","value":1},{"key":"chatPredictions","value":0},{"key":"guardrails","value":0}]}}
█ logEvent: CodyVSCodeExtension:abortButton:clicked VSCode {"properties":{"source":"sidebar"},"opts":{"hasV2Event":true}}
█ telemetry-v2: recordEvent: cody.sidebar.abortButton/clicked: {"parameters":{"version":0,"metadata":[{"key":"contextSelection","value":1},{"key":"chatPredictions","value":0},{"key":"guardrails","value":0}]}}
█ logEvent: CodyVSCodeExtension:recipe:chat-question:executed VSCode {"properties":{"requestID":"808ac33f-578b-449e-805e-d4c5633d41df","chatModel":"anthropic/claude-2.0","promptText":"wrong answer, it is 42","contextSummary":{}},"opts":{"hasV2Event":true}}
█ telemetry-v2: recordEvent: cody.recipe.chat-question/executed: {"parameters":{"version":0,"metadata":[{"key":"contextSelection","value":1},{"key":"chatPredictions","value":0},{"key":"guardrails","value":0}]}}
█ logEvent: CodyVSCodeExtension:recipe:chat-question:executed VSCode {"properties":{"requestID":"a09b9632-8ae6-4899-9dce-c722e0bfe2d6","chatModel":"anthropic/claude-2.0","promptText":"test","contextSummary":{}},"opts":{"hasV2Event":true}}
█ telemetry-v2: recordEvent: cody.recipe.chat-question/executed: {"parameters":{"version":0,"metadata":[{"key":"contextSelection","value":1},{"key":"chatPredictions","value":0},{"key":"guardrails","value":0}]}}

```

**Comment by jdorfman** [comment] 2023-12-13 21:33
Thanks @art-divin 

@taylorsperry this was from Discord. Here is a screenshot 
![image](https://github.com/sourcegraph/cody/assets/398230/84d542c2-81e1-43a4-948e-09259a8ea3ad)

**Comment by dominiccooney** [comment] 2023-12-14 00:09
This is new in simplified chats. Previously we silently managed truncating the context, now we show this banner. CC @beyang .

**Comment by beyang** [comment] 2023-12-29 22:31
Closing as a dupe of https://github.com/sourcegraph/cody/issues/2455

**Closed by beyang** 2023-12-29 22:31 UTC
Labels: bug, clients/vscode
