### ISSUE TITLE
bug: extension fails to focus when loading w/ new chat UI enabled

### ISSUE THREAD

**Issue by toolmantim** [sourcegraph/cody#1810] opened 2023-11-19 11:43 UTC
### Version

0.16.0

### Describe the bug

Trying to focus the extension sidebar quickly after window load can fail to focus the extension, forcing you to click it twice:

https://github.com/sourcegraph/cody/assets/153/ec2db545-4400-4727-8a55-41c5273dba0a

### Expected behavior

Extension sidebar stays focused while loading

**Comment by abeatrix** [comment] 2023-11-20 16:11
duplicate of https://github.com/sourcegraph/cody/issues/1757

**Closed by abeatrix** 2023-11-20 16:11 UTC
Labels: bug, clients/vscode, chat/commands
