### ISSUE TITLE
bug: Cody UI crashes occassionally when showing output, however results still displayed in the chat history.

### ISSUE THREAD

**Issue by erinmikailstaples** [sourcegraph/cody#5609] opened 2024-09-17 22:47 UTC
### Version

1.35

### Describe the bug

When working with cody to adjust errors, if you adjust the window panel size, the chat panel will crash.  However it will still run b/c it will show up in the history. 

Video file here: https://cln.sh/CVZwyMSz 

### Expected behavior

Expecting the chat to stay visible. 

### Additional context

<img width="1751" alt="image" src="https://github.com/user-attachments/assets/aa10a63d-6167-4df8-9732-a72feefb8b8c">

PS — @jdorfman rocks my socks

**Comment by theronburger** [comment] 2024-10-08 08:58
Is this a dupe of https://github.com/sourcegraph/cody/issues/5296?
I provide possible reasons here. spoiler alert, cody spams state hard and crashes it 
Recover the chat by restarting and going to history. 
Come on SourceGraph, fix this, its a huge pain

**Comment by PriNova** [comment] 2024-11-21 20:56
This issue is already resolved and will be closed.

**Closed by PriNova** 2024-11-21 20:56 UTC
Labels: bug, repo/cody
