### ISSUE TITLE
bug: GPTTurbo has no context

### ISSUE THREAD

**Issue by slaughters85j** [sourcegraph/cody#4150] opened 2024-05-10 17:25 UTC
### Version

The latest?

### Describe the bug

ChatGPT Turbo will not inspect files for context.  Sonnet does this well, but Turbo excludes files everytime.

### Expected behavior

Assess file provided via the @filename

Each time I provide references, it's automatically excluded and I get very bad suggestions.

**Comment by abeatrix** [comment] 2024-05-23 21:09
@slaughters85j Is this still an issue if you upgrade to v1.18.0+? You can verify the version number from the Cody settings&support sidebar (or via report issue where the version number will be pre-fill for you):

![image](https://github.com/sourcegraph/cody/assets/68532117/4b02ebb6-958a-4c01-a27e-03a137745b33)

If the issue persists after the upgrade, can you please share the following with us so that we can look into it for you? 😄 
- Is it GPT-3.5 Turbo or GPT-4 Turbo?
- Does it happen on new empty chat window?
- Your Cody output logs (click Export Logs) after reproducing the issue

**Comment by abeatrix** [comment] 2024-06-21 18:14
Closing since we are unable to reproduce the issue but please feel free to open this issue again if the latest version doesn't work for you. Thank you!

**Closed by abeatrix** 2024-06-21 18:14 UTC
Labels: bug, clients/vscode, cody
