### ISSUE TITLE
bug: enhanced context selector doesn't show any relevant information for enterprise users

### ISSUE THREAD

**Issue by kalanchan** [sourcegraph/cody#2275] opened 2023-12-11 23:58 UTC
### Version

v0.19.1702328753

### Describe the bug

When connected to an enterprise instance, users have no information around their embeddings if their repo is not indexed. 
![CleanShot 2023-12-11 at 15 53 58@2x](https://github.com/sourcegraph/cody/assets/51868853/99a9fd13-e3e4-4f4d-b12b-4e4ed8828fd2)

### Expected behavior

Users should see some information around their embeddings

**Comment by dominiccooney** [comment] 2023-12-13 03:06
I cannot reproduce this at f7cb9e5184c18f1a56b114b8a751f713079514f1.

**Comment by dominiccooney** [comment] 2023-12-13 03:10
I can reproduce this at v0.19.1702409542

**Comment by dominiccooney** [comment] 2023-12-13 03:11
It is timing related.

**Comment by dominiccooney** [comment] 2023-12-13 03:21
@kalanchan we should lower the severity of this. If you lose the race condition and trigger this state, all you have to do is open a file from the workspace and the context comes back. I think the important part isn't whether your repo has embeddings, it is how fast your workspace loads. So the user impact is low:

- Enterprise user
- Has to trigger a race condition
- Has to open chat without first opening a file from the workspace

It *is* a bug and we should fix it but I don't think this is a P1.

**Comment by dominiccooney** [comment] 2024-01-29 04:29
I am closing this, #2879 has refreshed this UX extensively. We show a "No repositories selected" and a button to select them, if there are no repositories selected automatically.

**Closed by dominiccooney** 2024-01-29 04:29 UTC
Labels: bug, clients/vscode
