### ISSUE TITLE
Automatic unit test file creation and updating

### ISSUE THREAD

**Issue by toolmantim** [sourcegraph/cody#1359] opened 2023-10-11 04:15 UTC
Generating unit tests currently outputs into chat. We want to make it similar to how `/doc` works, where it can just generate the tests for you, putting them in the right place (either a new file, or modifying any existing file).

**Comment by toolmantim** [comment] 2023-10-11 04:19
First version, using a code lens, and choosing to immediately open the file where possible:

![image](https://github.com/sourcegraph/cody/assets/153/55a7c4cd-3632-4c42-b951-c9b462824cd5)

Clickable prototypes:

1. [No existing test file](https://www.figma.com/proto/9112BsKsJc1BpO2j8XYwLL/%F0%9F%A4%96-Cody-VS-Code-%5BMain%5D?page-id=3250%3A136841&type=design&node-id=5345-10266&viewport=715%2C-4844%2C0.24&t=UX1nYHDtd3L3kQK3-9&scaling=min-zoom&starting-point-node-id=5345%3A10266&show-proto-sidebar=1)
2. [Test file already exists](https://www.figma.com/proto/9112BsKsJc1BpO2j8XYwLL/%F0%9F%A4%96-Cody-VS-Code-%5BMain%5D?page-id=3250%3A136841&type=design&node-id=5345-10312&viewport=715%2C-4844%2C0.24&t=UX1nYHDtd3L3kQK3-9&scaling=min-zoom&starting-point-node-id=5345%3A10312&show-proto-sidebar=1)
3. [Unknown test file name](https://www.figma.com/proto/9112BsKsJc1BpO2j8XYwLL/%F0%9F%A4%96-Cody-VS-Code-%5BMain%5D?page-id=3250%3A136841&type=design&node-id=5345-10358&viewport=715%2C-4844%2C0.24&t=UX1nYHDtd3L3kQK3-9&scaling=min-zoom&starting-point-node-id=5345%3A10358&show-proto-sidebar=1)

**Comment by abeatrix** [comment] 2023-10-11 20:28
My 2 cents:

> Do we need "Options"?
I suppose retry is good enough

 > Do we need the third unknown case above?
🤔 
 
 
> I've left off any link to chat. But do we want or need a link to open a chat? What would that even mean? Would people expect to be able to say "Retry that but with xyz" in the chat and it re-attempts the command?
Since we already have a shortcut to open chat, I don't think this is necessary.

**Comment by beyang** [comment] 2024-01-15 23:18
Closing as dupe of https://github.com/sourcegraph/cody/issues/1475. Please reopen if this is tracking something different.

**Closed by beyang** 2024-01-15 23:18 UTC
Labels: design, dec-ga/vscode
