### ISSUE TITLE
bug: cody screen is disappearing

### ISSUE THREAD

**Issue by SuperMoke** [sourcegraph/cody#5830] opened 2024-10-06 04:10 UTC
Type: <b>Bug</b>

## Extension Information

- Cody Version: 1.36.3
- VS Code Version: 1.94.0
- Extension Host: desktop

##  Steps to Reproduce

1. When i clicked the prompt or chat of the Cody when i click Shift + U the Cody contents like chat and stuff is disappearing

## Logs

Extension version: 1.36.3
VS Code version: Code 1.94.0 (d78a74bcdfad14d5d3b1b782f87255d802b57511, 2024-10-02T13:08:12.626Z)
OS version: Windows_NT x64 10.0.22631
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz (8 x 2419)|
|GPU Status|2d_canvas: unavailable_software<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>opengl: disabled_off<br>rasterization: disabled_software<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: disabled_software<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software<br>webgpu: unavailable_software<br>webnn: disabled_off|
|Load (avg)|undefined|
|Memory (System)|7.78GB (0.65GB free)|
|Process Argv|--crash-reporter-id 4fbfb2e7-6e2e-4cdd-8d63-9842bb6107c6|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805cf:30301675
binariesv615:30325510
vsaa593:30376534
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyonecf:30548226
962ge761:30959799
pythongtdpath:30769146
welcomedialog:30910333
pythonnoceb:30805159
asynctok:30898717
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
accentitlementst:30995554
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
da93g388:31013173
a69g1124:31058053
dvdeprecation:31068756
dwnewjupyter:31046869
2f103344:31071589
impr_priority:31102340
nativerepl1:31139838
refactort:31108082
pythonrstrctxt:31112756
flighttreat:31134774
wkspc-onlycs-t:31132770
nativeloc2:31134642
wkspc-ranged-t:31151552
cf971741:31144450
defaultse:31146405
notype1:31151523
cc771715:31146322

```

</details>

**Comment by Kynlos** [comment] 2024-10-07 00:09
By disappearing, do you mean the entire window goes blank, or just certain elements?

Any further info you can provide would be highly appreciated.

Thanks!

**Comment by SuperMoke** [comment] 2024-10-07 11:59
The entire windows of Cody is disappearing

**Comment by Kynlos** [comment] 2024-10-08 08:20
> The entire windows of Cody is disappearing.  For additional context on the chat panel i type the mention command which is the "@" when i type the u on my keyboard the entire cody is disappearing.
> 

So this is repeatable every single time you perform that action?

If so, would it be possible for you to record a short video of it happening, with the "Developer Tools" (Help > Toggle Developer Tools) window open in VSCode. This would be incredibly helpful.

Thanks!

**Comment by theronburger** [comment] 2024-10-08 08:54
This is a dupe of https://github.com/sourcegraph/cody/issues/5296
I provide possible reasons here. spoiler alert, cody spams state hard and crashes it

**Comment by PriNova** [comment] 2024-10-11 09:24
@SuperMoke 
Do you have Ollama installed and if yes, is it running as a service in the background?

**Comment by PriNova** [comment] 2024-11-21 20:59
This issue is already resolved and will be closed.

**Closed by PriNova** 2024-11-21 20:59 UTC
Labels: bug, repo/cody
