### ISSUE TITLE
bug: Grey cody window

### ISSUE THREAD

**Issue by treborjones** [sourcegraph/cody#5445] opened 2024-09-03 11:24 UTC
Type: <b>Bug</b>

## Extension Information

- Cody Version: 1.32.0
- VS Code Version: 1.92.2
- Extension Host: desktop

##  Steps to Reproduce

1. 10/11 questions in and it grey screened trying to resolve an error in the script. 
2.
3.

## Logs

Extension version: 1.32.6
VS Code version: Code 1.92.2 (fee1edb8d6d72a0ddff41e5f71a671c23ed924b9, 2024-08-14T17:29:30.058Z)
OS version: Windows_NT x64 10.0.22631
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i9-11900K @ 3.50GHz (16 x 3504)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|undefined|
|Memory (System)|63.88GB (41.90GB free)|
|Process Argv|D:\\Dev\\Bob\\My project (2)\\Library\\PackageCache\\com.unity.inputsystem@1.7.0\\InputSystem\\Plugins\\PlayerInput\\PlayerInputManager.cs --crash-reporter-id 76b230bd-c2c4-478a-ae93-aa17cd58a971|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805cf:30301675
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyonecf:30548226
962ge761:30959799
pythongtdpath:30769146
welcomedialog:30910333
pythonnoceb:30805159
asynctok:30898717
pythonregdiag2:30936856
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
accentitlementsc:30995553
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
jg8ic977:31013176
pythoncenvpt:31062603
a69g1124:31058053
dvdeprecation:31068756
dwnewjupyter:31046869
impr_priority:31102340
nativerepl1:31104043
refactort:31108082
pythonrstrctxt:31112756
flightc:31119335
wkspc-onlycs-c:31111717
wkspc-ranged-t:31123313
pme_test_c:31118331
ei213698:31121563

```

</details>

**Comment by theronburger** [comment] 2024-10-08 08:59
Is this a dupe of https://github.com/sourcegraph/cody/issues/5296?
I provide possible reasons here. spoiler alert, cody spams state hard and crashes it 
Recover the chat by restarting and going to history. 
Come on SourceGraph, fix this, its a huge pain

**Closed** 2024-11-21 20:56 UTC
Labels: bug, repo/cody
